// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlcsIUtIBvX0DcJZFc8yGSI09KF-jhuag',
    appId: '1:966300580112:android:1de389eef8808b7e304d95',
    messagingSenderId: '966300580112',
    projectId: 'agriflock-360-cb236',
    storageBucket: 'agriflock-360-cb236.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp_g1jSDl7MMBXoVqEb0CD038jsbPl08U',
    appId: '1:966300580112:ios:95f91eccf4389d3e304d95',
    messagingSenderId: '966300580112',
    projectId: 'agriflock-360-cb236',
    storageBucket: 'agriflock-360-cb236.firebasestorage.app',
    iosBundleId: 'com.mglobal.agriflock360',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp_g1jSDl7MMBXoVqEb0CD038jsbPl08U',
    appId: '1:966300580112:ios:95f91eccf4389d3e304d95',
    messagingSenderId: '966300580112',
    projectId: 'agriflock-360-cb236',
    storageBucket: 'agriflock-360-cb236.firebasestorage.app',
    iosBundleId: 'com.mglobal.agriflock360',
  );

}