// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlcsIUtIBvX0DcJZFc8yGSI09KF-jhuag',
    appId: '1:966300580112:android:36bd42e63555b260304d95',
    messagingSenderId: '966300580112',
    projectId: 'agriflock-360-cb236',
    storageBucket: 'agriflock-360-cb236.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp_g1jSDl7MMBXoVqEb0CD038jsbPl08U',
    appId: '1:966300580112:ios:d9e2c4fd4b4b8382304d95',
    messagingSenderId: '966300580112',
    projectId: 'agriflock-360-cb236',
    storageBucket: 'agriflock-360-cb236.firebasestorage.app',
    androidClientId: '966300580112-imqmadra66jmits9ah9km3lgcvmtjlpd.apps.googleusercontent.com',
    iosClientId: '966300580112-jjrj4naeftomrf8hedcub6soh96ug1g4.apps.googleusercontent.com',
    iosBundleId: 'com.mglobal.agriflock',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp_g1jSDl7MMBXoVqEb0CD038jsbPl08U',
    appId: '1:966300580112:ios:d9e2c4fd4b4b8382304d95',
    messagingSenderId: '966300580112',
    projectId: 'agriflock-360-cb236',
    storageBucket: 'agriflock-360-cb236.firebasestorage.app',
    androidClientId: '966300580112-imqmadra66jmits9ah9km3lgcvmtjlpd.apps.googleusercontent.com',
    iosClientId: '966300580112-jjrj4naeftomrf8hedcub6soh96ug1g4.apps.googleusercontent.com',
    iosBundleId: 'com.mglobal.agriflock',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEg8aegC5KCa0wppqj9a6vkudQQC-HMnM',
    appId: '1:966300580112:web:2e8d5cb04e7dea79304d95',
    messagingSenderId: '966300580112',
    projectId: 'agriflock-360-cb236',
    authDomain: 'agriflock-360-cb236.firebaseapp.com',
    storageBucket: 'agriflock-360-cb236.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEg8aegC5KCa0wppqj9a6vkudQQC-HMnM',
    appId: '1:966300580112:web:02aa5b426dd25ea8304d95',
    messagingSenderId: '966300580112',
    projectId: 'agriflock-360-cb236',
    authDomain: 'agriflock-360-cb236.firebaseapp.com',
    storageBucket: 'agriflock-360-cb236.firebasestorage.app',
  );

}